umco/umbraco-ditto

- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
I've updated the check on propertyValue to check for IsNullOrWhiteSpace() because GetPropertyValue
was returning an empty string rather than null therefore not using my AltPropertyName or the
DefaultValue if set.
Nice one,
Aaron ( - First pull request so go easy! Think I've done it right...)
> Property Value Null Checks

- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Extensions/TypeInitializationExtensions.cs
- src/Our.Umbraco.Ditto/ModelFactory/DittoPublishedContentModelFactory.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj.DotSettings
Replaces the cache hack with private threadsafe dictionaries for storing
constructor and parameter info to reduce reflection overhead. This
should solve both issue #3 and also prevent circular referencing bugs
noted in the forums.
Additionally an extension method has been added for type initialisation.
This allow much faster creation of instance types than
Application.CreateInstance.
Refactorings are also present from other pull request.
> Adding performance improvements

- src/Our.Umbraco.Ditto/ModelFactory/DittoPublishedContentModelFactory.cs
Added null-reference check for `UmbracoContext.PublishedContentRequest`.
This applies to when the model-factory is called from the back-office context (e.g. a Save & Publish call).
Fixes #14 :suspect:
> Workaround null-reference exceptions from non-frontend calls

- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
This will allow the type converter implementations to use dependency injection, so they're more testable etc.
> Use DependencyResolver to load TypeConverters

- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Extensions/TypeInferenceExtensions.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
This addition allows us to detect custom TypeConverter attributes for enumerable types. This lets us add the TypeConverter attribute to the type argument class itself rather than each property which dramatically cuts down fluff. 
Adding the TypeConverter attribute to the property will override any attributes bound to classes.
E.g
```
[TypeConverter(typeof(FooConverter))]
public class Foo
{
// Properties here
}
public class Bar
{
// This property will automatically map
public IEnumerable<Foo> Foos { get; set; }
}
```
> Parse TypeConverter attributes on enumerables

- src/Our.Umbraco.Ditto/Extensions/TypeInitializationExtensions.cs
@JimBobSquarePants - Following on from #20 - do you see any issue with us swapping out using `Activator` with `DependencyResolver`?
> TypeInitializationExtensions - use DependencyResolver?

- src/Our.Umbraco.Ditto/ComponentModel/ConverterHelper.cs
- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/ContentPickerConverter.cs
- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/HtmlStringConverter.cs
- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/MediaPickerConverter.cs
- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/MultiNodeTreePickerConverter.cs
- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/MultipleMediaPickerConverter.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj.DotSettings
This adds the following converters:
- HtmlStringConverter
- ContentPickerConverter
- MediaPickerConverter
- MultipleMediaPickerConverter
- MultiNodeTreePickerConverter
Additionally a helper class has been added (internally for now) that aids with the conversion process by supplying a per-request-cached `UmbracoHelper` instance.
I've also made `HtmlString` conversion part of the default conversion pipeline. It makes more sense to me to have this run automatically than to add an attribute to the property each time.
> Adding built in TypeConverters

- src/Our.Umbraco.Ditto/Attributes/UmbracoDictionaryValueAttribute.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
Added support for Umbraco Dictionary Item values.
I'm not 100% happy about having a private static field for `UmbracoHelper`, but I didn't want to create a new instance for each property mapping - otherwise the Dictionary lookup may hit the database multiple times.
// @JimBobSquarePants - feel free to add suggestions
> Added support for Umbraco Dictionary Item values.

- BuildPackage/Build.bat
- BuildPackage/package.proj
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- src/Our.Umbraco.Ditto/Properties/VersionInfo.cs
- src/Our.Umbraco.Ditto/packages.config
Reverted the System.Web.Mvc dependency from v4.0.0.1 back to v4.0.0.0.
As this is causing issues with environments that have not yet been patched with v4.0.0.1 yet.
This patch should resolve issue #27.
> Hotfix 0.5.1

- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
This commit add passing the current IPublishedContent as a context to
TypeConverters.
With this addition it's now possible to use `context.Instance` within custom `TypeConverters`
public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
{
IPublishedContent content
if (context != null)
{
content = (IPublishedContent)context.Instance;
}
// Do the conversion.
}
This is great if you need to substitute values when converting. E.g Substituting `SeoTitle` with `Name`
> Adds a context to the conversions.

- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Extensions/RenderModelExtensions.cs
Enabling the current culture to be passed into the conversion.
> Adds a `CultureInfo` parameter to the `.As<T>` extension methods.

- appveyor.yml
- build/package.proj
This will cause the build scripts to generate both a .nupkg and a symbols.nupkg.
The nupkg will contain exactly the same contents as it does currently, the symbols.nupkg will additionally contain the pdb file and all cs files, this package will be automatically pushed to symbolsource.org (no config needed) and Visual Studio will be able to debug if set to use symbol servers!
> Adding support for SymbolSource for both NuGet and MyGet

- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
allows a TypeConverter to be executed for a null, such as when a value hasn't been set in Umbraco, or for when a property doesn't actually store a value (eg. nuPickers: Relation Labels)
> Allow TypeConverters to be called when property value is null

- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
The methods in this class were getting too difficult to follow and any changes difficult to detect. Resharper was having a hard time also.
I've split the `GetPropertyValue` method into two parts: a getter and a setter. I've also cached the `MethodInfo` instances for `Cast` and `FirstOrDefault` as static fields since they will never change.That should give us a performance booster.
@leekelleher @mattbrailsford Can you both cast your eyes over this when you can as I want to make sure I haven't introduced any bugs?
> Refactoring PublishedContentExtensions for readability and performance.

- appveyor.yml
- build/package.proj
- build/tools/AppVeyorUmbraco/AppVeyorUmbraco.Targets
Six digit leading zero build numbers
Build numbers suffixed with a hyphen, e.g. "0.7.0-alpha-000022"
CI builds always have a suffix, by default "alpha" but could also be "beta"
If using "beta" CI build and then want to move to RTM, can now use special "rtm" suffix, set UMBRACO_PACKAGE_PRERELEASE_SUFFIX = rtm, when you release via lightweight tag, one build will be the release and will be successful, the other will intentionally fail to avoid a invalid CI build.
This allows this full release pattern if you want it:
version: 0.7.0.{build}
UMBRACO_PACKAGE_PRERELEASE_SUFFIX=
CI > 0.7.0-alpha-0012
CI > 0.7.0-alpha-0013
UMBRACO_PACKAGE_PRERELEASE_SUFFIX=alpha
APPVEYOR_REPO_TAG=true
Release > 0.7.0-alpha
UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
CI > 0.7.0-beta-0015
APPVEYOR_REPO_TAG=true
Release > …
> Implement new build naming & numbering

- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/AppSettingValueResolver.cs
- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/CurrentContentAsValueResolver.cs
- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/DittoValueResolver.cs
- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/UmbracoDictionaryValueResolver.cs
- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/UmbracoPropertyValueResolver.cs
- tests/Our.Umbraco.Ditto.Tests/MockValueResolverTests.cs
- tests/Our.Umbraco.Ditto.Tests/Models/ComplexModel.cs
Currently when you create a value resolver, you have to override a ResolveValue function that has a bunch of params that get passed through, for example: 
What I've done in this pull request is added a bunch of props to the ValueResolver class to hold these params, and simplified the ResolveValue method to a parameterless function
An added advantage to this is that I've also added a Content property which casts the context.instance property to IPublishedContent as this is going to be a common action.
The only negative in my eyes is that it isn't entirely obvious what properties are available to you, though I think this could be resolved with some documentation. My imediate feeling though is that less code = better.
What do you guys think?
> Looking at option to make cleaner value resolvers

- src/Our.Umbraco.Ditto/ComponentModel/ConversionHandlers/DittoConversionHandlerRegistry.cs
- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/DittoValueResolver.cs
- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/DittoValueResolverRegistry.cs
- src/Our.Umbraco.Ditto/Ditto.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- tests/Our.Umbraco.Ditto.Tests/ConversionHandlerTests.cs
- tests/Our.Umbraco.Ditto.Tests/GlobalValueResolverTests.cs
- tests/Our.Umbraco.Ditto.Tests/Models/CalculatedModel.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
- tests/Our.Umbraco.Ditto.Tests/PublishedContentTests.cs
During a discussion with @leekelleher he came up with a scenario that is not currently supported by the new conversion handlers which was previously supported by the events system which was having the ability to modify objects during conversion that are outside our control (ie, we can't add the conversion handler attributes to them).
Rather than reinstating the events system, what I have here is something similar to how TypeDescriptor works in that it allows you to register a handler for a type at runtime. The syntax for this is:
Ditto.RegisterConversionHandler<MyObject, MyHandler>();
What this is saying is during the conversion of any object of type MyObject run the MyHandler conversion handler during it's conversion.
One thing @leekelleher and I were unsure of was the use of the Ditto …
> Register Global Conversion Handlers

- appveyor.yml
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- tests/Our.Umbraco.Ditto.Tests/ClassLevelTypeConverterTests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
I found that if a TypeConverter's `CanConvertFrom` returns false, then the property's value is assigned a `null` reference.
I have added a fix, so that we check if the value type matches the target property's type, then we can assigned it.
It's probably easier to review the attached unit-test: [`ClassLevelTypeConverterTests`](https://github.com/leekelleher/umbraco-ditto/blob/hotfix-0.8.1/tests/Our.Umbraco.Ditto.Tests/ClassLevelTypeConverterTests.cs)
> Rejected TypeConverter value returns null

- src/Our.Umbraco.Ditto/ComponentModel/ConversionHandlers/DittoConversionHandlerRegistry.cs
- tests/Our.Umbraco.Ditto.Tests/MultipleConversionHandlerTests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
The value type for `DittoConversionHandlerRegistry`'s internal `Cache` was being cast as an array, rather than a `List<Type>`.
This lead to a `NotSupportedException` ("Collection was of a fixed size.") when registering multiple conversion-handlers.
I've added a unit-test to support this fix.
@mattbrailsford I've assigned to you for a sanity check.
> Fixes DittoConversionHandlerRegistry cache type-cast

- src/Our.Umbraco.Ditto/Extensions/Internal/TypeInferenceExtensions.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- tests/Our.Umbraco.Ditto.Tests/EnumerableDetectionTests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
- tests/Our.Umbraco.Ditto.Tests/TypeInferenceTests.cs
I've stumped up on a bug with how Ditto is determining if a property is an `Enumerable` type.
If a property is using a generic `Dictionary<T1, T2>` type, Ditto will attempt to cast the value as `Enumerable<T1>`.
I've added a unit-test to verify this scenario, see [`EnumerableDetectionTests`](https://github.com/leekelleher/umbraco-ditto/blob/bug/enumerable-detection/tests/Our.Umbraco.Ditto.Tests/EnumerableDetectionTests.cs), I think it's easier to explain in code.
Here's an example of the exception thrown...
```
Test Name:	GenericDictionary_Property_Is_Detected_As_Enumerable
Test FullName:	Our.Umbraco.Ditto.Tests.EnumerableDetectionTests.GenericDictionary_Property_Is_Detected_As_Enumerable
Test Source:	x:\umbraco-ditto\tests\Our.Umbraco.Ditto.Tests\EnumerableDetectionTests.cs : line 41 …
```
> Generic Dictionary detected as Enumerable

- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/UmbracoPropertyValueResolver.cs
- tests/Our.Umbraco.Ditto.Tests/CustomPublishedContentPropertyTests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
@Jeavon [raised an issue on Gitter](https://gitter.im/leekelleher/umbraco-ditto?at=5603f6cbe85e8d337252aa51) about Ditto not mapping the value of a property when using a custom `IPublishedContent` that has a property with the same name.
I have modified the `UmbracoPropertyValueResolver` to handle this scenario, (and included a supporting unit-test).
We first try to get the value from the `IPublishedContent` object property, then if the value is null, we make a call to the content's `GetPropertyValue` method.
---
@JimBobSquarePants @mattbrailsford Could either of you cast an eye over this change and scenario, (most as a sanity check), thanks.
@Jeavon If you want to try out a custom build from this branch to confirm that this works for you?
> Custom PublishedContent property nullifies value

- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/DittoContentPickerConverter.cs
- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/DittoMediaPickerConverter.cs
- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/DittoMemberPickerConverter.cs
- src/Our.Umbraco.Ditto/ComponentModel/TypeConverters/DittoMultipleMediaPickerConverter.cs
Following on from issue #127 ...
Marked the legacy TypeConverters with the `Obsolete` attribute, as they have been superseded by `DittoPickerConverter`.
Are we happy with the warning message?
"This converter has been deprecated, please use the DittoPickerConverter instead."
> Deprecate legacy Ditto TypeConverters?

- tests/Our.Umbraco.Ditto.Tests/ImageCropDataSetMappingTests.cs
- tests/Our.Umbraco.Ditto.Tests/Models/ImageCropModels.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
Discussions around ImageCrop values/models keep arising, this unit-test is intended to clarify that the values can be mapped using Ditto.
Opening as PR, so to allow for any discussion. Do we need this unit-test in the Ditto core?
> Unit-test for ImageCropDataSet

- src/Our.Umbraco.Ditto/Extensions/Internal/TypeInferenceExtensions.cs
- tests/Our.Umbraco.Ditto.Tests/TypeInferenceTests.cs
Hey @JimBobSquarePants, here's one for you :smirk_cat: 
Whilst experimenting with returning collections of a custom `IPublishedContent` class, Ditto wouldn't attempt to cast/map them any further.
I set up a quick unit-test to see if this was the case... (where `PublishedContentMock` is a custom implementation of `IPublishedContent`)
```
typeof(IEnumerable<Mocks.PublishedContentMock>).IsEnumerableOfType(typeof(IPublishedContent))
```
Should this be true or false?
---
I've added in a fix that swaps around the params for the `IsAssignableFrom` check.
> Testing IPublishedContent with IsEnumerableOfType extension method

- src/Our.Umbraco.Ditto/ComponentModel/PublishedContentContext.cs
- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/DittoValueResolverContext.cs
- src/Our.Umbraco.Ditto/ComponentModel/ValueResolvers/UmbracoPropertyValueResolver.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- tests/Our.Umbraco.Ditto.Tests/InheritedClassWithPrefixedPropertyTests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
Added a unit-test to verify the issue raised in #132 by @jamiepollock
The problem is that the Context in `UmbracoPropertyValueResolver` is not aware of the derived class.
It only knows about the `ComponentType`, which is the class that the property is bound to, (e.g. the inherited/base class).
> Unit-test for inherited classes with prefixed properties

- src/Our.Umbraco.Ditto/ComponentModel/Attributes/DittoDefaultProcessorAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/DittoProcessorRegistry.cs
- src/Our.Umbraco.Ditto/Ditto.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- tests/Our.Umbraco.Ditto.Tests/DefaultProcessorTests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
Proposed solution to issue #151
Adds a way to register the default processor type, either globally or at class-level.
Includes unit-tests to support this feature.
> Default Processor Type

- docs/install.md
- src/Our.Umbraco.Ditto.PerformanceTests/App.config
- src/Our.Umbraco.Ditto.PerformanceTests/Our.Umbraco.Ditto.PerformanceTests.csproj
- src/Our.Umbraco.Ditto.PerformanceTests/Program.cs
- src/Our.Umbraco.Ditto.PerformanceTests/Properties/AssemblyInfo.cs
- src/Our.Umbraco.Ditto.PerformanceTests/packages.config
- src/Our.Umbraco.Ditto.sln
- src/Our.Umbraco.Ditto/Common/CachedInvocations.cs
- src/Our.Umbraco.Ditto/Common/EnumerableInvocations.cs
- src/Our.Umbraco.Ditto/Common/MethodBaseCacheItem.cs
- src/Our.Umbraco.Ditto/Common/PropertyInfoInvocations.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoPropertyAttribute.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- src/Our.Umbraco.Ditto/Properties/AssemblyInfo.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
Add compiled cached PropertyInfo accessors and benchmarking code.
This more than doubles the speed on my machine. Hopefully it should do the same on everyone else's. I'd love to see if somehow we could use the performance of dynamic but as far as I'm aware there's no way to get or set the properties without knowing the name at compile time.
:horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: 
```
// * Summary *
BenchmarkDotNet=v0.9.4.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=AMD A6-3410MX APU with Radeon(tm) HD Graphics, ProcessorCount=4
Frequency=14318180 ticks, Resolution=69.8413 ns, Timer=HPET
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE …
```
> Fast property accessors

- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoPickerAttribute.cs
- tests/Our.Umbraco.Ditto.Tests/Mocks/MockHttpContext.cs
- tests/Our.Umbraco.Ditto.Tests/Mocks/MockPublishedContentCache.cs
- tests/Our.Umbraco.Ditto.Tests/Mocks/MockPublishedMediaCache.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
- tests/Our.Umbraco.Ditto.Tests/UmbracoPickerProcessorTests.cs
Following a discussion with @mattbrailsford earlier today, I started to play with mocking the UmbracoContext in order to test the UmbracoPicker processor.
So far I have manually mocked things like HttpContextBase and the PublishedContent/MediaCache objects - we may find that a mocking library (such as Moq) would be better, but I have limited knowledge on that... (totally open to advice on that!)
The interesting part about testing UmbracoPicker is that we can remove the subsequent `.As(targetType)` calls, as when a processor returns an `IPublishedContent` object, it will automagically check the target type and process further.
---
I've opened as a pull-request to gauge feedback on the mocking approach... and to check that @JimBobSquarePants is happy with the `.As(targetType)` removal …
> Unit-test UmbracoPicker processor

- src/Our.Umbraco.Ditto/Common/PropertyInfoInvocations.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- tests/Our.Umbraco.Ditto.Tests/InternalSetterTests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
- tests/Our.Umbraco.Ditto.Tests/SetMethodTests.cs
A proposed fix for issue #172 - on assigning property value of internal setter
> Proposed fix for assigning property value of internal setter

- src/Our.Umbraco.Ditto/Common/DittoDisposableTimer.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoPropertiesAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoPropertyAttribute.cs
- src/Our.Umbraco.Ditto/Ditto.cs
- tests/Our.Umbraco.Ditto.Tests/BasicMappingTests.cs
- tests/Our.Umbraco.Ditto.Tests/Mocks/MockLogger.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
- tests/Our.Umbraco.Ditto.Tests/PropertySourceMappingTests.cs
This is a fix for issue #184. 
Added code to allow you to select a property source when using UmbracoPropertyAttribute so that you can define the order in which properties are checked between the instance properties and properties in the umbraco properties collection. This can be set per property using the PropertySource parameter of the UmbracoPropertyAttribute, or globally by setting Ditto.DefaultPropertySource in an app startup handler. If using either InstanceThenUmbracoProperties (the default) or UmbracoThenInstanceProperties and the site is in debug mode, and ditto detects that the property requested hides a property in the other source, then a warning log message will be logged to the log file giving instructions to either not use reserved aliases, or to use PropertySource to …
> Adds PropertySource to UmbracoPropertyAttribute 

- src/Our.Umbraco.Ditto/ComponentModel/Attributes/DittoMultiProcessorAttribute.cs
- tests/Our.Umbraco.Ditto.Tests/MultiProcessorTests.cs
During Code Cabin 16 (woo #codecabin16!) @mattbrailsford asked us to remind him to add an empty constructor to DittoMultiProcessorAttribute. Instead I've added in the code myself (feature sniping! :/)
The reason for this was to allow more sophisticated parameter/property binding through the inherited DittoMultiProcessorAttribute.
Example of this would be the following.
```csharp
public class TitleAttribute : DittoMultiProcessorAttribute
{
public string TitlePropertyAlias { get; set; }
public TitleAttribute()
{
base.Attributes.AddRange(new[]
{
new UmbracoPropertyAttribute(TitlePropertyAlias),
new AltUmbracoPropertyAttribute("Name")
});
}
}
```
Where as the traditional way to achieve a similar thing would be:
```csharp
public class TitleAttribute : DittoMultiProcessorAttribute
{
public …
```
> Adding an empty constructor to DittoMultiProcessorAttribute

- src/Our.Umbraco.Ditto/ComponentModel/Attributes/DittoLazyAttribute.cs
- src/Our.Umbraco.Ditto/Ditto.cs
- src/Our.Umbraco.Ditto/Extensions/Internal/MemberInfoExtensions.cs
- src/Our.Umbraco.Ditto/Extensions/Internal/PropertyInfoExtensions.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/LazyLoad.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- tests/Our.Umbraco.Ditto.Tests/LazyTests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
As discussed in #190, adding a DittoLazy attribute to be explicit about which properties are Lazy loaded.
@JimBobSquarePants can you check at line 385 that this is ok? In the original code, virtual props were made first, and this code ran, THEN non virtual property values were set. Should this be ok that all properties are set first lazy and non lazy, and THEN the proxy object is created?
Still need to do some unit tests
> DittoLazy attribute

- src/Our.Umbraco.Ditto/ComponentModel/Processors/DittoProcessorRegistry.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/RecursiveDittoAttribute.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
If a processor returns an `IPublishedContent`, then the recursive processor (one of the default post-processors) will make an `.As()` call, but it doesn't pass in current `DittoProcessorContext` objects.  This pull-request aims to resolve this.
@mattbrailsford Are you happy with the processor contexts being passed through to `GetPostProcessorAttributes()`?
> RecursiveDitto processor doesn't maintain the ProcessorContexts

- tests/Our.Umbraco.Ditto.Tests/Issue177Tests.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
Added failing unit-test for issue #177
When using proxy classes, it appears that lazy-loaded properties can not access the property values of its object instance.
@JimBobSquarePants to review (in due course - no rush, just wanted to keep track of this) :sunglasses:
> Proxy class properties accessing object instance properties

- src/Our.Umbraco.Ditto/Common/DittoContextAccessor.cs
- src/Our.Umbraco.Ditto/Ditto.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- tests/Our.Umbraco.Ditto.Tests/GlobalSetupFixture.cs
- tests/Our.Umbraco.Ditto.Tests/Mocks/MockDittoContextAccessor.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
With references to PR #212, one of the queries (from PR #204) was the naming of `IUmbracoApplicationContextAccessor`.  How's about renaming it to `IDittoContextAccessor`?
> IUmbracoApplicationContextAccessor rename

- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoXPathAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoXPathNavigatorAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoXPathProcessorAttribute.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
This can be used if you need a more raw/direct query to get data from the content-cache.
Also refactored the current XPath processor, extracted out the reusable parts into an `UmbracoXPathProcessor` base class.
---
In terms of a use-case, for an events listing page, I needed a dropdown list of all the "in-use" years from the events.  I'd previously got the event listing node, looped over all the event-page child nodes, got the event date, built up a list, etc. It worked fine, but not very efficient.
Since the Umbraco content-cache can give you direct access to `GetXPathNavigator()`, we can use a direct XPath query to get the aggregated data.
Here's my usage...
```csharp
[InUseYears("$current/ancestor-or-self::homepage/eventListing[1]/eventPage/eventDate[normalize-space(.)]")]
public …
```
> XPathNavigator Processor

- src/Our.Umbraco.Ditto/ComponentModel/ConversionHandlers/DittoConversionHandlerContext.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
When handling a conversion event/delegate, it could be useful to have access to the current culture info via the context.
> Added Culture to DittoConversionHandlerContext

- src/Our.Umbraco.Ditto/ComponentModel/ConversionHandlers/DittoConversionHandlerContext.cs
Following on from #215, this PR makes the `DittoConversionHandlerContext` mark the properties setters as `protected internal`
Hopefully, this will help clear any confusion about the context properties (e.g. the IPublishedContent) being assignable.
> Makes the DittoConversionHandlerContext property setters internal

- src/Our.Umbraco.Ditto/ComponentModel/ConversionHandlers/DittoConversionHandler.cs
- src/Our.Umbraco.Ditto/ComponentModel/ConversionHandlers/DittoConversionHandlerContext.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- tests/Our.Umbraco.Ditto.Tests/ConversionHandlerTests.cs
- tests/Our.Umbraco.Ditto.Tests/MultipleConversionHandlerTests.cs
**Forewarning: Breaking Change**
@mattbrailsford You're gonna hate on me for this! :laughing:
After adding the `Culture` property to `DittoConversionHandlerContext ` (in PR #216). I'd later noticed that I'd missed adding it on `DittoConversionHandler`.
Which got me thinking, why are we duplicating properties here? Wouldn't it be better to access the Content, Model, ModelType (and now Culture) via a Context property?
> Which is conceptually the same as we do in Processors - and the method-level `DittoOnConvertedAttribute` - those properties hang off a context object.
Of course, this being a breaking change, I don't take it lightly, hence seeking peer approval. ❤️
> DittoConversionHandler - replace Content/Model properties with a Context property

- src/Our.Umbraco.Ditto/Web/Mvc/DittoView.cs
@mattbrailsford - I'd found an scenario a while back where if a `DittoView<T>` page referenced another `DittoView<T>` page, but the view-model was castable, the code wouldn't cast it and Ditto would recreate the object.
That might sound like a mouthful, but I'll try to explain...
Say you've got these POCOs...
```csharp
public class MasterModel
{
public string Something { get; set; }
}
public class OtherModel : MasterModel
{
public string Whatever { get; set; }
}
```
If you had `DittoView<OtherModel>` on a page template, and `DittoView<MasterModel>` on the layout template, the DittoView code would be creating the object twice, rather than downcasting it to the inherited type.
This PR adds in a check to see if the model object is a `DittoViewModel<>` and to unwrap the inner view-model, so …
> DittoView: Enhancement to support unwrapping & downcasting view-models

- src/Our.Umbraco.Ditto/ComponentModel/Processors/DittoProcessorRegistry.cs
- src/Our.Umbraco.Ditto/Ditto.cs
@mattbrailsford What are you're thoughts on the implementation?
A basic list with the register/unregister methods, wrapping the list's add/insert/remove methods.
I'd looked at making the entire post-processors list replaceable, but `RecursiveDittoAttribute` and `TryConvertToAttribute` are marked as internal, so that wasn't ideal, (and I don't want to change those to public).
For the unregister one, it gives me the option to exclude the `HtmlString` processor when I don't need it.
> Post processors - Adds methods to register/deregister

- src/Our.Umbraco.Ditto/ComponentModel/Processors/DittoProcessorRegistry.cs
As discussed on PR #223 review: https://github.com/leekelleher/umbraco-ditto/pull/223#discussion_r136792514
> DefaultProcessorType - makes static and adds lock

- appveyor.yml
- src/Our.Umbraco.Ditto/Extensions/Internal/PropertyInfoExtensions.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Proxy/LazyInterceptor.cs
- src/Our.Umbraco.Ditto/Proxy/PropertyEmitter.cs
- src/Our.Umbraco.Ditto/Proxy/ProxyFactory.cs
- tests/Our.Umbraco.Ditto.Tests/Our.Umbraco.Ditto.Tests.csproj
- tests/Our.Umbraco.Ditto.Tests/ProxyFactoryTests.cs
So it turns out setting properties for proxied instances was broken for value types.
We got away with it because we actually had two instances of the mapped type (one proxied and one not) on the go at one time. (obviously not efficient) and were setting the property on the hidden copy.
This PR fixes that and also changes the interceptor to only attempt to intercept the lazy properties (as removing the copy would create an infinite recursion of interception)
We also don't now attempt to create a proxy from a non-null instance as that would simply replace the instance.
> Fix proxy generation

- src/Our.Umbraco.Ditto/ComponentModel/Attributes/DittoMultiProcessorAttribute.cs
When using a Ditto multi-processor, the base `UmbracoContext` and `ApplicationContext` are null (not set).
This fix sets the values based on the current instances (from the multi-processor).
> DittoMultiProcessor doesn't set UmbracoContext

- src/Our.Umbraco.Ditto/ComponentModel/Processors/DittoProcessorRegistry.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
Refactored to return an instance of the processor rather than the type.
We were previously passing around the `Type` of the default processor, rather than getting an instance of it when we required it.
This is an internal API, no breaking-changes here.
> Internal refactor - Get Default Processor instance not type

- src/Our.Umbraco.Ditto/Bootstrapper.cs
- src/Our.Umbraco.Ditto/ComponentModel/ObjectResolution/AttributedTypeResolver.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/DittoProcessorRegistry.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoPropertyAttribute.cs
- src/Our.Umbraco.Ditto/Ditto.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- src/Our.Umbraco.Ditto/Our.Umbraco.Ditto.csproj
- tests/Our.Umbraco.Ditto.Tests/GlobalSetupFixture.cs
Adds a resolver class to provide a lookup for specific Ditto attributes for a given type.
The thinking behind this is that we have a few places where we check for a custom attribute, e.g. the `UmbracoProperties` attribute inside the `UmbracoProperty` processor.
Given that this is called for each object's property, it has the potential of being queried a lot of times.
Of course this adds time to app startup, but then it's a once-off operation.
Would like to know your thoughts on this approach.
> Attributed Type Resolver

- src/Our.Umbraco.Ditto/ComponentModel/Attributes/DittoProcessorAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Caching/DittoCacheContext.cs
- src/Our.Umbraco.Ditto/ComponentModel/Caching/DittoDefaultCacheKeyBuilder.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/AppSettingAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/Contexts/DittoProcessorContext.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/CurrentContentAsAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/DittoFactoryAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/EnumAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/EnumerableConverterAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/HtmlStringAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/RecursiveDittoAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/TryConvertToAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoDictionaryAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoPickerAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/Processors/UmbracoPropertyAttribute.cs
- src/Our.Umbraco.Ditto/Extensions/PublishedContentExtensions.cs
- tests/Our.Umbraco.Ditto.Tests/EnumerableConverterTests.cs
- tests/Our.Umbraco.Ditto.Tests/ExtremeChainedContextTests.cs
The reason we're using the `PropertyDescriptor` is due to Ditto original use of TypeConverters.
When we rolled up the TypeConverters and ValueResolvers, we'd kept `PropertyDescriptor` available.
However the use of reflection in Ditto's internals, there is an additional call made to exclusively get the `PropertyDescriptor`. If we switch this to use the `PropertyInfo`, (which we already have a local reference to), then this can be used to access any metadata about the property itself.
So not to make this a rough breaking-change, I'd left the `PropertyDescriptor` property available on the Contexts, so not to completely ruin the developer experience.  I added an obsolete/warning message saying that it would be removed in a future release.
Does anyone foresee any downsides with this approach?
> Deprecate PropertyDescriptor in Contexts

- src/Our.Umbraco.Ditto/ComponentModel/Attributes/DittoProcessorAttribute.cs
- src/Our.Umbraco.Ditto/ComponentModel/ObjectResolution/AttributedTypeResolver.cs
Second attempt to fix #238 
---
I originally thought that using a `ConcurrentDictionary` would mitigate from the concurrency issue, as outlined in issue #238. But that doesn't appear to be the case.  I'm not sure why we'd want to use a `ConcurrentDictionary` if it's not working as expected - _which, is most likely due to my understanding of how it actually works._  This patch changes from using `ConcurrentDictionary` to a regular generic `Dictionary`, adding locks to prevent concurrently issues between reads/writes.
> AttributedTypeResolver - Adds locks to prevent concurrency issue

- src/Our.Umbraco.Ditto/Web/Mvc/DittoView.cs
- src/Our.Umbraco.Ditto/Web/Mvc/Models/DittoViewModel.cs
- src/Our.Umbraco.Ditto/Web/Mvc/Models/IDittoViewModel.cs
Extends the `DittoView` directive to declare the strongly-typed model for the `IPublishedContent` (generated by ModelsBuilder).
The usage would be...
```csharp
@inherits DittoView<ContentPage, MyViewModel>
@Model.Content // strongly-typed as ContentPage
@Model.View // strong-typed as MyViewModel
```
I've tried to keep the API backwards-compatible, but it did require changes to `BaseDittoViewModel`, so it's a breaking-change, (although someone would have to be doing some advanced stuff if they are using `BaseDittoViewModel`).
> DittoView - Adds support for ModelsBuilder
